const DEFAULT_TARGET_PROJECT = process.env.VERCEL_PROJECT_ID || "prj_EZxcYfhL0X0yvC3ov1KrksRR8r0k";

function json(res,status,payload){
  res.status(status).setHeader("Content-Type","application/json");
  res.end(JSON.stringify(payload));
}

function classifyTask(task){
  const t=String(task||"").toLowerCase();
  if(/website|web page|landing page|site/.test(t)) return "WEBSITE";
  if(/github|commit|repository|repo/.test(t)) return "GITHUB";
  if(/deploy|vercel|hosting/.test(t)) return "DEPLOY";
  return "UNSUPPORTED";
}

function buildWebsite(task){
  const safeTask=String(task||"").replace(/[<>]/g,"").slice(0,180);
  const html=`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Max Generated Website</title>
<style>
*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:#0b1020;color:#eef2ff;font-family:system-ui,sans-serif}
main{width:min(760px,90vw);padding:48px;border:1px solid #33405d;border-radius:24px;background:#121a2b;box-shadow:0 24px 80px #0008}
h1{font-size:clamp(32px,7vw,64px);margin:0 0 16px}p{color:#aab6cf;line-height:1.7}.badge{display:inline-block;padding:8px 12px;border-radius:999px;background:#243455;color:#9fc0ff;font-size:12px;font-weight:700;letter-spacing:.08em}
</style></head><body><main><span class="badge">GENERATED BY MAX</span><h1>Website ready.</h1><p>Task: ${safeTask || "Create a website"}</p><p>This is the first live execution capability of the JARVIS AI Office.</p></main></body></html>`;
  return html;
}

async function deployToVercel(html,name){
  const token=process.env.VERCEL_TOKEN;
  if(!token) throw new Error("VERCEL_TOKEN is not configured in Vercel.");
  const response=await fetch("https://api.vercel.com/v13/deployments",{
    method:"POST",
    headers:{"Authorization":`Bearer ${token}`,"Content-Type":"application/json"},
    body:JSON.stringify({
      name:name||"max-generated-site",
      project:DEFAULT_TARGET_PROJECT,
      files:[{file:"index.html",data:html}],
      projectSettings:{framework:null}
    })
  });
  const data=await response.json();
  if(!response.ok) throw new Error(data?.error?.message||"Vercel deployment failed.");
  return {id:data.id,url:data.url?("https://"+data.url):null,readyState:data.readyState||"QUEUED"};
}

export default async function handler(req,res){
  if(req.method!=="POST") return json(res,405,{ok:false,error:"POST required"});
  try{
    const body=typeof req.body==="string"?JSON.parse(req.body||"{}"):(req.body||{});
    const task=String(body.task||"").trim();
    if(!task) return json(res,400,{ok:false,error:"Task is required."});
    const type=classifyTask(task);
    if(type!=="WEBSITE"){
      return json(res,200,{ok:true,mode:"planned",status:"UNSUPPORTED",message:"The real execution gateway is online, but this first capability only executes website-generation tasks.",type});
    }
    const html=buildWebsite(task);
    const deployment=await deployToVercel(html,"max-generated-site");
    return json(res,200,{ok:true,mode:"executed",status:"DEPLOYED",type,result:{message:"Website generated and sent to Vercel.",url:deployment.url,deploymentId:deployment.id,readyState:deployment.readyState}});
  }catch(error){
    return json(res,500,{ok:false,status:"ERROR",error:error?.message||"Execution failed."});
  }
}
